import Box from "@/components/Box";
import Card from "@/components/Card";
import Text from "@/components/Text";
import { theme } from "@/styles/theme";
import { Button } from "@/components/Buttons";
import { TDisputeProps } from "../types";

const Disputes = ({ disputes }: TDisputeProps) => {
  return (
    <Box
      wid="100%"
      flexDirection="column"
      justifyContent="flex-start"
      alignItems="flex-start"
      marginTop={20}
    >
      <Text
        fontSize={theme.fonts.sizes.md}
        color={theme.colors.base.secondary}
        weight={500}
      >
        Disputes
      </Text>
      <Text
        fontSize={theme.fonts.sizes.sm}
        color={theme.colors.base.gray[300]}
        marginBottom={15}
      >
        List of disputes generated by the user
      </Text>
      {disputes.length === 0 ? (
        <Card>
          <Text
            fontSize={theme.fonts.sizes.sm}
            color={theme.colors.base.red[200]}
          >
            Select a letter option from the side menu
          </Text>
        </Card>
      ) : (
        disputes.map((dispute) => {
          return <Card key={dispute.id}>{dispute.template}</Card>;
        })
      )}
      {disputes.length > 0 && (
        <Box wid="100%" justifyContent="flex-end">
          <Button
            wid="25%"
            justifyContent="center"
            backgroundColor={theme.colors.base.secondary}
            fontSize={theme.fonts.sizes.md}
            fontColor={theme.colors.base.white}
            type="submit"
            // icon={
            //   loading && (
            //     <Loading
            //       size={theme.icons.sizes.xs}
            //       color={theme.colors.base.white}
            //     />
            //   )
            // }
            marginTop={10}
            marginBottom={5}
          >
            <Text
              fontSize={theme.fonts.sizes.md}
              color={theme.colors.base.white}
              weight={500}
              pointerEvents="none"
            >
              {/* {!loading && "Login"} */}
              Create Letter
            </Text>
          </Button>
        </Box>
      )}
    </Box>
  );
};

export default Disputes;
