import Box from "@/components/Box";
import Card from "@/components/Card";
import InputText from "@/components/Inputs/Text";
import Text from "@/components/Text";
import { theme } from "@/styles/theme";
import ArrowTurnUpRight from "./icons/ArrowTurnUpRight";
import ArrowTurnDownRight from "./icons/ArrowTurnDownRight";
import { Button } from "@/components/Buttons";
import Copy from "./icons/Copy";
import Radio from "@/components/Inputs/Radio";
import { useState } from "react";

const Disputes = () => {
  const [bureau, setBureau] = useState<string>("");

  return (
    <Box
      wid="100%"
      flexDirection="column"
      justifyContent="flex-start"
      alignItems="flex-start"
      marginTop={20}
    >
      <Text
        fontSize={theme.fonts.sizes.md}
        color={theme.colors.base.secondary}
        weight={500}
      >
        Disputes
      </Text>
      <Text
        fontSize={theme.fonts.sizes.sm}
        color={theme.colors.base.gray[300]}
        marginBottom={15}
      >
        List of disputes generated by the user
      </Text>
      <Card>
        <Box wid="100%" justifyContent="space-between">
          <Text
            fontSize={theme.fonts.sizes.md}
            color={theme.colors.base.secondary}
            weight={500}
          >
            Charge-offs
          </Text>
          <Box hover="cursor:pointer;">
            <Text
              fontSize={theme.fonts.sizes.md}
              color={theme.colors.base.red[200]}
              weight={500}
              pointerEvents="none"
            >
              Delete
            </Text>
          </Box>
        </Box>
        <Box wid="30%" marginTop={10} justifyContent="space-between">
          <Radio
            label="Equifax"
            onChange={() => setBureau("equifax")}
            checked={bureau === "equifax"}
            marginRight={10}
          />
          <Radio
            label="Experian"
            onChange={() => setBureau("experian")}
            checked={bureau === "experian"}
            marginRight={10}
          />
          <Radio
            label="TransUnion"
            onChange={() => setBureau("transunion")}
            checked={bureau === "transunion"}
            marginRight={10}
          />
        </Box>
        <Box
          wid="100%"
          flexDirection="row"
          justifyContent="flex-start"
          alignItems="center"
          marginTop={20}
        >
          <InputText
            wid="35%"
            label="Data Furnisher"
            placeholder="5/5/2023"
            marginRight={10}
          />
          <InputText
            wid="35%"
            label="Account#"
            placeholder="5/5/2023"
            marginRight={10}
          />
          <InputText wid="30%" label="Balance" placeholder="5/5/2023" />
        </Box>
        <Box
          wid="100%"
          flexDirection="column"
          justifyContent="flex-start"
          alignItems="flex-start"
          marginTop={10}
        >
          <Box
            wid="100%"
            justifyContent="flex-start"
            alignItems="flex-end"
            marginBottom={5}
          >
            <ArrowTurnUpRight
              size={theme.icons.sizes.sm}
              margin={`0 0 0 10px`}
            />
            <InputText
              wid="100%"
              label="Action to be taken"
              placeholder="5/5/2023"
              marginLeft={10}
            />
          </Box>
          <Button fontSize={theme.fonts.sizes.md}>Reverse</Button>
          <Box
            wid="100%"
            justifyContent="flex-start"
            alignItems="flex-start"
            marginTop={5}
          >
            <ArrowTurnDownRight
              size={theme.icons.sizes.sm}
              margin={`0 0 0 10px`}
            />
            <InputText
              wid="100%"
              label="Justifyer for action"
              placeholder="5/5/2023"
              marginLeft={10}
            />
          </Box>
        </Box>
        <Box
          wid="100%"
          flexDirection="row"
          justifyContent="flex-start"
          alignItems="center"
          marginTop={10}
        >
          <InputText
            wid="33%"
            label="EXPERIAN Shows"
            placeholder="5/5/2023"
            marginRight={10}
          />
          <InputText
            wid="33%"
            label="EQUIFAX Shows"
            placeholder="5/5/2023"
            marginRight={10}
          />
          <InputText
            wid="33%"
            label="TRANSUNION Shows"
            placeholder="5/5/2023"
          />
        </Box>
        <Box
          wid="100%"
          flexDirection="row"
          justifyContent="flex-start"
          alignItems="center"
          marginTop={10}
        >
          <InputText
            wid="100%"
            label="Additional Comment"
            placeholder="5/5/2023"
          />
        </Box>
        <Box
          wid="100%"
          flexDirection="row"
          justifyContent="flex-end"
          alignItems="center"
          marginTop={10}
        >
          <Button icon={<Copy size={theme.icons.sizes.sm} />}>
            Duplicate this dispute
          </Button>
        </Box>
      </Card>
    </Box>
  );
};

export default Disputes;
